load_data('EQPegB_both_pha2.fits')
load_arf(4, 'eqpegMEG_1_garf.fits')
load_rmf(4, 'eqpeg_meg1_rmf.fits')
set_analysis('wave')
group_counts(4, 10)
plot_data(4, linestyle='solid', yerrorbars=False, marker=None)
load_data('EQPegB_pha2.fits')
load_arf(4, 'eqpegMEG_1_garf.fits')
load_rmf(4, 'eqpeg_meg1_rmf.fits')
set_analysis('wave')
group_counts(4, 10)
plot_data(4, overplot=True, linestyle='solid', yerrorbars=False, marker=None)
xlim(4, 15)

title("Contamination the EQ Peg B spectrum by EQ Peg A")
savefig("eqpeg_spectra.png", bbox_inches='tight')
savefig("eqpeg_spectra.pdf", bbox_inches='tight')


load_data('EQPegB_both_pha2.fits')
load_arf(4, 'eqpegMEG_1_garf.fits')
load_rmf(4, 'eqpeg_meg1_rmf.fits')
set_analysis('wave')
subtract(4)
group_counts(4, 10)
plot_data(4)
xlim(4, 15)

title("Background-subtracted spectrum of  EQ Peg B spectrum")
savefig("eqpeg_background.png", bbox_inches='tight')
savefig("eqpeg_background.pdf", bbox_inches='tight')
